#!/usr/bin/env bash
docker run \
    --name zigbee2mqtt_dining \
    --restart=unless-stopped \
    -p 8082:8080 \
    -v /Users/glandix/zigbee2mqtt_dining/data:/app/data \
    -v /run/udev:/run/udev:ro \
    -e TZ=America/Chicago \
	-d \
    koenkk/zigbee2mqtt
