#!/usr/bin/env bash
docker run \
    --name z2m-dining \
    --restart=unless-stopped \
    --ip 192.168.0.15 \
	--dns 192.168.0.13 \
    --dns-search home \
    --network slacknet-0 \
    -v ./data:/app/data \
    -v /run/udev:/run/udev:ro \
    -e TZ=America/Chicago \
    -d \
    koenkk/zigbee2mqtt
